repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.0
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.10.0
    hooks:
      - id: mypy
        args: [--strict]
        additional_dependencies: [pytest]

  - repo: local
    hooks:
      - id: pytest
        name: pytest
        entry: pytest semaine-05/Pre-commit-strict-et-code-review
        language: system
        types: [python]
        pass_filenames: false

      - id: no-print-or-naked-todo
        name: Interdire print() et TODO anonymes
        entry: python semaine-05/Pre-commit-strict-et-code-review/check_code.py
        language: python
        types: [python]