"""ajout isbn a books

Revision ID: 61321b21aa72
Revises: 0348520689b0
Create Date: 2026-08-21 16:54:55.635427

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '61321b21aa72'
down_revision: Union[str, Sequence[str], None] = '0348520689b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('isbn', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('books', 'isbn')
    # ### end Alembic commands ###
