"""drop old isbn column

Revision ID: 6d86c2f625f1
Revises: 7e82ceded868
Create Date: 2026-08-20 18:36:08.591165

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d86c2f625f1'
down_revision: Union[str, Sequence[str], None] = '7e82ceded868'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('books', 'isbn')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('isbn', sa.VARCHAR(), nullable=False))
    # ### end Alembic commands ###
